title: Fluffy Life
author: Bella the spitz
email: your-email@domain.com
description: > this is where you can find your soul mate

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
